### ISSUE TITLE
Add Multiarch support for simple demo operator

### ISSUE THREAD

**Issue by vikasmulaje** [opdev/simple-demo-operator#2]

**Comment by komish** [comment]
/assign

@vikasmulaje I'm working on this. Per our discussion, you specifically want ppc64le support which I will work towards first. If that's not the case, let me know.

**Comment by komish** [comment]
@vikasmulaje please review https://github.com/opdev/simple-demo-operator/releases/tag/v0.0.6 which should add ppc64le support, and close this out when you've determined this works for you.

**Comment by komish** [comment]
@vikasmulaje Given the 0.0.6 release should solve this problem, I'll close this out. Please feel free to create a subsequent issue if the operator does not properly support multi-arch as you expect.
